지원 취소
---
tags:
  - Application
description: "사용자가 지원한 채용 공고의 지원을 취소합니다."
parameters:
  - in: path
    name: id
    description: "취소할 지원의 ID"
    required: true
    type: integer
    example: 1
responses:
  200:
    description: "지원이 성공적으로 취소되었습니다."
    schema:
      type: object
      properties:
        code:
          type: integer
          example: 200
        args:
          type: object
          description: "요청에 전달된 매개변수"
        message:
          type: string
          description: "성공 메시지"
          example: "Application with ID 1 has been deleted"
  400:
    description: "유효하지 않은 요청입니다."
    schema:
      type: object
      properties:
        code:
          type: integer
          example: 400
        args:
          type: object
          description: "요청에 전달된 매개변수"
        message:
          type: string
          description: "오류 메시지"
          example: "Invalid request"
  404:
    description: "지원 내역을 찾을 수 없습니다."
    schema:
      type: object
      properties:
        code:
          type: integer
          example: 404
        args:
          type: object
          description: "요청에 전달된 매개변수"
        message:
          type: string
          description: "오류 메시지"
          example: "Application not found"
  409:
    description: "지원이 이미 취소된 상태입니다."
    schema:
      type: object
      properties:
        code:
          type: integer
          example: 409
        args:
          type: object
          description: "요청에 전달된 매개변수"
        message:
          type: string
          description: "오류 메시지"
          example: "Application with Id 1 is already canceled"
  500:
    description: "서버 오류가 발생했습니다."
    schema:
      type: object
      properties:
        code:
          type: integer
          example: 500
        args:
          type: object
          description: "요청에 전달된 매개변수"
        message:
          type: string
          description: "오류 메시지"
          example: "Internal server error"
